### ISSUE TITLE
Compile Error with Arduino IDE

### ISSUE THREAD

**Issue by roelleke** [ancalex/Perpetual-Calendar-with-Google-Calendar-Connection#1]
Hello,
i tried to compile your Software with the Arduino IDE. But i got an error on a missing declaration:
`F:\Downloads\esp8266\41. Perpedual Calender\Perpetual_Calendar_with_Google_Calendar_Connection\ColorCodedClock.h: In function 'void timeDisplay(byte, byte, byte)':
ColorCodedClock.h:6:3: error: 'leds' was not declared in this scope
    6 |   leds[i] = CRGB(0, 0, 0);
      |   ^~~~
ColorCodedClock.h:6:13: error: 'CRGB' was not declared in this scope
    6 |   leds[i] = CRGB(0, 0, 0);
      |             ^~~~
ColorCodedClock.h:12:2: error: 'leds' was not declared in this scope
   12 |  leds[62] = rainbow_colors[first];
      |  ^~~~
ColorCodedClock.h:12:13: error: 'rainbow_colors' was not declared in this scope
   12 |  leds[62] = rainbow_colors[first];
      |             ^~~~~~~~~~~~~~
In file included from D:\Benutzer\Dieter\Dokumente\Arduino\libraries\FastLED\src/FastLED.h:67,
                 from F:\Downloads\esp8266\41. Perpedual Calender\Perpetual_Calendar_with_Google_Calendar_Connection\Perpetual_Calendar_With_Google_Calendar_Connection.ino:8:
D:\Benutzer\Dieter\Dokumente\Arduino\libraries\FastLED\src/fastspi.h: At global scope:
D:\Benutzer\Dieter\Dokumente\Arduino\libraries\FastLED\src/fastspi.h:145:23: note: '#pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output'
  145 | #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
exit status 1
'leds' was not declared in this scope`

I used the Version 1.8.19 of the IDE. All Libriaries are up to date.

**Comment by ancalex** [comment]
When you open the ino file in Arduino IDE it asks to make a folder with the name......
it will copy only the ino file, you will need also the rest of the files there
or when you unzip the code, before opening the ino file change the main folder name to match with the ino file name

**Comment by roelleke** [comment]
I did that, of course, but the error is still there.

**Comment by ancalex** [comment]
For me everything is compiling fine
I'm using Arduino IDE 1.8.16, FastLED 3.3, esp board 2.7.4

**Comment by ancalex** [comment]
I updated fastled to 3.5.0
compiles fine
update Arduino IDE to 1.8.19
compiling ok

**Comment by roelleke** [comment]
I, now tried the Arduino IDE 2.0.0 Beta. This IDE detects an Error in the Foldername. I can't found the Error therefore I suggested an hidden character. I wrote the complete name new and now it compiles.
Thanks for your help.

**Comment by ancalex** [comment]
I'm glad it worked.
